### ISSUE TITLE
Clicked event screen

### ISSUE THREAD

**Issue by callumf222** [callumf222/Setap#6]
- A pop up screen over main screen for adding an event.
- Desc, Data, Tag, add button.
- Doesn't need to function with javascript, just need the HTML and CSS design of the screen.
- Does not need to wait for home screen implementation, can use a temporary background and use Z-index to be place over the top

**Comment by up2047715** [comment]
Have Code outputting to an array which is the event value. All info from array can be added into the csv we use for storing events.

Still need to iron out error checking and etc in the html side with displaying errors being caught and catching them in the js code.

**Comment by up2047715** [comment]
Have given each value a defined type, need to do errors
